cmake_minimum_required(VERSION 3.21)

project(ob_csharp VERSION 2.4.0 LANGUAGES CSharp)

set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/install)

file(GLOB_RECURSE SOURCES src/*.cs)

add_library(${PROJECT_NAME} SHARED ${SOURCES})

set_property(TARGET ${PROJECT_NAME} PROPERTY DOTNET_SDK "Microsoft.NET.Sdk")
set_property(TARGET ${PROJECT_NAME} PROPERTY DOTNET_TARGET_FRAMEWORK "net8.0")
set_property(TARGET ${PROJECT_NAME} PROPERTY DOTNET_LANGUAGE_VERSION "latest")
set_property(TARGET ${PROJECT_NAME} PROPERTY DOTNET_ENABLE_DEFAULT_ITEMS TRUE)

if (WIN32)
    message(STATUS "Building for Windows (.NET 8)")
    file(GLOB OB_SDK_LIB_FILES ${CMAKE_CURRENT_LIST_DIR}/OrbbecSDK/lib/OrbbecSDK.dll)
    file(GLOB OB_SDK_EXT_DIR ${CMAKE_CURRENT_LIST_DIR}/OrbbecSDK/lib/extensions)
    file(GLOB OB_SDK_CONFIG_FILES ${CMAKE_CURRENT_LIST_DIR}/OrbbecSDK/config/OrbbecSDKConfig.*)
elseif (UNIX)
    message(STATUS "Building for Linux (.NET 8)")
    file(GLOB OB_SDK_LIB_FILES ${CMAKE_CURRENT_LIST_DIR}/OrbbecSDK/lib/libOrbbecSDK.so)
    file(GLOB OB_SDK_EXT_DIR ${CMAKE_CURRENT_LIST_DIR}/OrbbecSDK/lib/extensions)
    file(GLOB OB_SDK_CONFIG_FILES ${CMAKE_CURRENT_LIST_DIR}/OrbbecSDK/config/OrbbecSDKConfig.*)
else()
    message(FATAL_ERROR "Unsupported platform!")
endif()

install(FILES ${OB_SDK_LIB_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
install(DIRECTORY ${OB_SDK_EXT_DIR} DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)
install(FILES ${OB_SDK_CONFIG_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/bin)

install(FILES ${OB_SDK_LIB_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
install(DIRECTORY ${OB_SDK_EXT_DIR} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
install(FILES ${OB_SDK_CONFIG_FILES} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)

install(TARGETS ${PROJECT_NAME}
    RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
    LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
    ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
)

# if (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/samples/CMakeLists.txt")
#     add_subdirectory(samples)
# endif()
